# Generated by Django 4.1.6 on 2023-04-03 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_event_delete_errandmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="errand",
            new_name="is_errand",
        ),
    ]
